static const char black[]       = "#222526";
static const char gray2[]       = "#a3be8c"; // unfocused window border
//static const char gray2[]       = "#2e3440"; // unfocused window border
static const char gray3[]       = "#5d6061";
static const char gray4[]       = "#6d8dad";
static const char blue[]        = "#bf616a";  // focused window border
static const char green[]       = "#89b482";
static const char red[]         = "#ec6b64";
static const char orange[]      = "#d6b676";
static const char yellow[]      = "#d1b171";
static const char pink[]        = "#cc7f94";
static const char col_borderbar[]  = "#222526"; // inner border
